function material = gen_material(Z, R, density)
%GEN_MATERIAL (Z, R) Generate the attenuation function by energy for
%material with atomic weights Z, ratios R and the material density.
%   Input a 1D array of atomic weights, a 1D array of ratios, and a scalar value
%   for density in g/cm^3.
%   Output a function handle of attenuation function by energy.
%   The attenuation function is generated by using the package PhotonAttenuation 
%   by Jaroslaw Tuszynski (https://uk.mathworks.com/matlabcentral/fileexchange/12092-photonattenuation).
%   PhotonAttenuationQ is used to, inputting the atomic weight and energy, then 
%   summing the attenuation coefficients of each element weighted by the ratio.
%   The attenuation function is then scaled by the density.
    R = R/sum(R); % Normalize the ratio
    material = @(E) sum(PhotonAttenuationQ(Z, E, 1) .* R) * density;
end